language: python

env:
    - CONDA="python=2.7"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - conda config --add channels ioos -f
    - travis_retry conda create --yes -n test $CONDA --file requirements.txt
    - source activate test
    - travis_retry conda install --yes pytest
    - conda info -a
    # GUI
    #- "export DISPLAY=:99.0"
    #- "sh -e /etc/init.d/xvfb start"

script:
    - py.test --verbose --doctest-modules --ignore setup.py
